fix: chmod for stupid archives (sometimes upnpacked permissions are weird)
new: more error reporting

diff --git a/formatdoc b/formatdoc
--- a/formatdoc
+++ b/formatdoc
@@ -1,7 +1,7 @@
 #!/bin/bash
+error=0
 
-if [ -z "$1" ]
-  then
+if [ -z "$1" ]; then
     echo "This script is used to pretty-print all XML files inside ODF or OOXML package file."
     echo
 	echo "Usage:"
@@ -9,19 +9,36 @@ if [ -z "$1" ]
 	exit
 fi
 
+error_handle()
+{
+    error=1
+    echo "Error: $1"
+    rm -rf $TMPDIR || echo "Cleanup failure!"
+    exit 1
+}
+
+
 TMPDIR=$(mktemp -d -t ci-XXXXXXXXXX)
 FILENAME=$(basename "$1")
 
-unzip "$1" -d $TMPDIR > /dev/null
+unzip -D "$1" -d $TMPDIR > /dev/null || error_handle "unzip fails!"
+chmod -R 744 $TMPDIR
 
 find $TMPDIR -type f -name "*.xml" -o -type f -name "*.rels" | while read filename; do
-	xmllint --format "${filename}" > "${filename}2"
-	mv "${filename}2" "${filename}"  > /dev/null
+	xmllint --format "${filename}" > "${filename}2" || error_handle "xmllint fails!"
+	mv "${filename}2" "${filename}"  > /dev/null || error_handle "mv fails!"
 done
 
+# Check while loop errors
+if [ "$error" -gt 0 ]; then
+    echo "${error}!"
+    echo ":("
+    exit 1
+fi
+
 pushd $TMPDIR > /dev/null
-zip "$FILENAME" -r . > /dev/null
+zip "$FILENAME" -r . > /dev/null || error_handle "zipping fails!"
 popd > /dev/null
 
 mv "$TMPDIR/$FILENAME" "$1"  > /dev/null
-rm -rf $TMPDIR
+rm -rf $TMPDIR || echo "Cleanup failure"
